[mgr] # File list.
prepend_keymap = [
	# Goto
	{ on = [ "g", "C" ], run = "cd ~/code", desc = "Goto ~/code" },
	{ on = [ "g", "D" ], run = "cd ~/documents", desc = "Goto ~/documents" },
    { on = [ "g", "d" ], run = "cd ~/downloads", desc = "Goto ~/downloads" },
	{ on = [ "g", "m" ], run = "cd ~/music", desc = "Goto ~/music" },
	{ on = [ "g", "p" ], run = "cd ~/pictures", desc = "Goto ~/pictures" },
	{ on = [ "g", "v" ], run = "cd ~/videos", desc = "Goto ~/videos" },
	{ on = [ "g", "r" ], run = "cd /", desc = "Goto /" }
]

# [tasks] # Task manager.
# [spot] # File information spotter.
# [pick] # Pick component. e.g. "open with" for files.
# [input] # Input component. e.g. create, rename, etc
# [confirm] # Confirmation dialog. e.g. remove, overwrite, etc.
# [completion] # Completion component. e.g. "cd" path completion
# [help] # Help menu.

