[mgr]
ratio = [1, 3, 3]
sort_sensitive = false
sort_dir_first = true
linemode = "size"
show_hidden = true
show_symlink = true

[opener]
open = [
	{ run = 'xdg-open "$@"', desc = "xdg-open" },
]

[input]
cursor_blink = true

